=== object71/vcpkg-skeleton/vcpkg/scripts/vcpkg.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "title": "Vcpkg manifest",
  "description": "Vcpkg manifest file. See https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md.",
  "definitions": {
    "identifier": {
      "description": "Identifiers used for feature names.",
      "allOf": [
        {
          "description": "Identifier are lowercase with digits and dashes.",
          "type": "string",
          "pattern": "[a-z0-9]+(-[a-z0-9]+)*"
        },
        {
          "not": {
            "description": "Identifiers must not be a Windows filesystem or vcpkg reserved name.",
            "type": "string",
            "pattern": "^prn|aux|nul|con|lpt[1-9]|com[1-9]|core|default$"
          }
        }
      ]
    },
    "package-name": {
      "description": "Name of a package.",
      "allOf": [
        {
          "description": "Package name must be a dot-separated list of valid identifiers",
          "type": "string",
          "pattern": "^[a-z0-9]+(-[a-z0-9]+)*(\\.[a-z0-9]+(-[a-z0-9]+)*)*$"
        },
        {
          "not": {
            "description": "Identifiers must not be a Windows filesystem or vcpkg reserved name.",
            "type": "string",
            "pattern": "(^|\\.)(prn|aux|nul|con|lpt[1-9]|com[1-9]|core|default)(\\.|$)"
          }
        }
      ]
    },
    "description-field": {
      "description": "A string or array of strings containing the description of a package or feature.",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      ]
    },
    "dependency-object": {
      "description": "Expanded form of a dependency with explicit features and platform.",
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/package-name"
        },
        "features": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/identifier"
          }
        },
        "default-features": {
          "type": "boolean",
          "default": true
        },
        "platform": {
          "$ref": "#/definitions/platform-expression"
        }
      },
      "patternProperties": {
        "^\\$": {}
      },
      "required": [
        "name"
      ],
      "additionalProperties": false
    },
    "dependency": {
      "description": "A dependency fetchable by Vcpkg.",
      "oneOf": [
        {
          "$ref": "#/definitions/package-name"
        },
        {
          "$ref": "#/definitions/dependency-object"
        }
      ]
    },
    "platform-expression": {
      "description": "A specification of a set of platforms. See https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md#definitions.",
      "type": "string"
    },
    "feature": {
      "description": "A package feature that can be activated by consumers.",
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/identifier"
        },
        "description": {
          "$ref": "#/definitions/description-field"
        },
        "dependencies": {
          "description": "Dependencies used by this feature.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/dependency"
          }
        }
      },
      "patternProperties": {
        "^\\$": {}
      },
      "required": [
        "name",
        "description"
      ],
      "additionalProperties": false
    }
  },
  "type": "object",
  "properties": {
    "name": {
      "$ref": "#/definitions/package-name"
    },
    "version-string": {
      "description": "A string without semantic meaning, equivalent to `CONTROL`'s `Version` field.",
      "type": "string"
    },
    "port-version": {
      "description": "A non-negative integer. If this field doesn't exist, it's assumed to be `0`.",
      "type": "integer",
      "minimum": 0,
      "default": 0
    },
    "maintainers": {
      "description": "An array of strings which contain the authors of a package",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "description": {
      "$ref": "#/definitions/description-field"
    },
    "homepage": {
      "description": "A url which points to the homepage of a package.",
      "type": "string",
      "format": "uri"
    },
    "documentation": {
      "description": "A url which points to the documentation of a package.",
      "type": "string",
      "format": "uri"
    },
    "license": {
      "description": "An SPDX license expression at version 3.9.",
      "type": "string"
    },
    "dependencies": {
      "description": "Dependencies that are always required.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/dependency"
      }
    },
    "dev-dependencies": {
      "description": "Dependencies only required for developers (testing and the like).",
      "type": "array",
      "items": {
        "$ref": "#/definitions/dependency"
      }
    },
    "features": {
      "description": "An array of features supported by the package",
      "type": "array",
      "items": {
        "$ref": "#/definitions/feature"
      }
    },
    "default-features": {
      "description": "Features enabled by default with the package.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/identifier"
      }
    },
    "supports": {
      "$ref": "#/definitions/platform-expression"
    }
  },
  "patternProperties": {
    "^\\$": {}
  },
  "required": [
    "name",
    "version-string"
  ],
  "additionalProperties": false
}

=== object71/vcpkg-skeleton/ports/comms/vcpkg.json
{
  "name": "comms",
  "version-string": "3.1.2",
  "description": "COMMS is the C++(11) headers only, platform independent library, which makes the implementation of a communication protocol to be an easy and relatively quick process.",
  "homepage": "https://commschamp.github.io/",
  "documentation": "https://github.com/commschamp/comms_champion"
}

=== object71/vcpkg-skeleton/vcpkg/ports/portaudio/vcpkg.json
{
  "name": "portaudio",
  "version-string": "2020-02-02",
  "port-version": 2,
  "description": "PortAudio Portable Cross-platform Audio I/O API PortAudio is a free, cross-platform, open-source, audio I/O library.  It lets you write simple audio programs in 'C' or C++ that will compile and run on many platforms including Windows, Macintosh OS X, and Unix (OSS/ALSA). It is intended to promote the exchange of audio software between developers on different platforms. Many applications use PortAudio for Audio I/O.",
  "homepage": "https://app.assembla.com/spaces/portaudio/wiki",
  "supports": "!uwp"
}

=== object71/vcpkg-skeleton/ports/gmp/vcpkg.json
{
  "name": "gmp",
  "version-string": "6.2.0",
  "port-version": 5,
  "description": "The GNU Multiple Precision Arithmetic Library",
  "homepage": "https://gmplib.org",
  "dependencies": [
    {
      "name": "vs-yasm",
      "platform": "windows"
    },
    {
      "name": "yasm-tool-helper",
      "platform": "windows"
    }
  ]
}

=== object71/vcpkg-skeleton/vcpkg/ports/commsdsl/vcpkg.json
{
  "name": "commsdsl",
  "version-string": "3.5.4",
  "description": "DSL schemas parser and code generator for CommsChampion Ecosystem",
  "homepage": "https://commschamp.github.io/",
  "documentation": "https://github.com/commschamp/commsdsl",
  "supports": "!uwp",
  "dependencies": [
    "boost-algorithm",
    "boost-filesystem",
    "boost-program-options",
    "libxml2"
  ]
}

=== object71/vcpkg-skeleton/ports/libass/vcpkg.json
{
  "name": "libass",
  "version-string": "0.14.0",
  "port-version": 3,
  "description": "libass is a portable subtitle renderer for the ASS/SSA (Advanced Substation Alpha/Substation Alpha) subtitle format",
  "homepage": "https://github.com/libass/libass",
  "dependencies": [
    {
      "name": "dirent",
      "platform": "windows"
    },
    "freetype",
    "fribidi",
    "harfbuzz"
  ]
}

=== object71/vcpkg-skeleton/vcpkg/ports/dartsim/vcpkg.json
{
  "name": "dartsim",
  "version-string": "6.9.4",
  "description": "Dynamic Animation and Robotics Toolkit",
  "homepage": "https://dartsim.github.io/",
  "dependencies": [
    "assimp",
    "boost-algorithm",
    "boost-filesystem",
    "boost-functional",
    "boost-lexical-cast",
    "boost-math",
    "boost-optional",
    "boost-regex",
    "boost-system",
    "bullet3",
    "ccd",
    "eigen3",
    "fcl",
    "octomap",
    "ode",
    "tinyxml2",
    "urdfdom"
  ]
}
